export const SEARCH_MOVIES = 'SEARCH_MOVIES'

export const START_SEARCH = 'START_SEARCH'
export const CANCELLED_SEARCH = 'CANCELLED_SEARCH'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'